In [1]:
import numpy as np

def apply_convolution(input_matrix, kernel, stride=1, padding_type='same'):
    input_size = np.array(input_matrix.shape)
    kernel_size = np.array(kernel.shape)

    if padding_type == 'same':
        pad_h = (kernel_size[0] - 1) // 2
        pad_w = (kernel_size[1] - 1) // 2
        input_padded = np.pad(input_matrix, ((pad_h, pad_h), (pad_w, pad_w)), mode='constant', constant_values=0)
    elif padding_type == 'valid':
        pad_h, pad_w = 0, 0
        input_padded = input_matrix  # No padding applied
    else:
        raise ValueError("Invalid padding type. Use 'same' or 'valid'.")

    padded_size = np.array(input_padded.shape)

    output_h = ((padded_size[0] - kernel_size[0]) // stride) + 1
    output_w = ((padded_size[1] - kernel_size[1]) // stride) + 1

    output_matrix = np.zeros((output_h, output_w))

    for i in range(0, output_h):
        for j in range(0, output_w):
            region = input_padded[i * stride : i * stride + kernel_size[0], j * stride : j * stride + kernel_size[1]]
            output_matrix[i, j] = np.sum(region * kernel)

    return output_matrix

# Example Input Image (8x8) - Replace with your own matrix
input_matrix = np.array([
    [0.1, 0.3, 0.5, 0.7, 0.2, 0.9, 0.4, 0.8],
    [0.6, 0.2, 0.8, 0.1, 0.5, 0.7, 0.3, 0.4],
    [0.9, 0.4, 0.6, 0.3, 0.8, 0.2, 0.7, 0.1],
    [0.5, 0.8, 0.1, 0.4, 0.6, 0.9, 0.2, 0.3],
    [0.7, 0.1, 0.3, 0.8, 0.2, 0.4, 0.9, 0.6],
    [0.2, 0.9, 0.4, 0.7, 0.1, 0.5, 0.3, 0.8],
    [0.3, 0.5, 0.7, 0.2, 0.9, 0.4, 0.6, 0.1],
    [0.8, 0.1, 0.2, 0.6, 0.3, 0.7, 0.5, 0.9]
])

# Example Kernel (3x3)
kernel = np.array([
    [0.2, -0.5, 0.3],
    [-0.4, 0.8, -0.1],
    [0.6, -0.3, 0.5]
])

# Change stride and padding type as needed
stride = 1
padding_type = 'same'  # Can be 'valid' or 'same'

# Apply Convolution
output_matrix = apply_convolution(input_matrix, kernel, stride, padding_type)

# Print the output
print("Convolution Output Matrix:")
print(output_matrix)


Convolution Output Matrix:
[[-0.03  0.85  0.14  1.04  0.05  0.84  0.41  0.54]
 [ 0.43  0.58  0.78  0.19  0.64  0.81  0.1   0.27]
 [ 0.69  0.27  0.61  0.42  0.99 -0.2   1.21 -0.31]
 [-0.17  1.13 -0.04  0.47  0.57  1.18 -0.24  0.61]
 [ 0.93 -0.45  1.12  0.58  0.49 -0.06  1.28 -0.05]
 [-0.09  1.16  0.19  0.92 -0.02  1.16 -0.12  0.73]
 [ 0.17  0.47  0.83 -0.36  1.46 -0.02  1.22 -0.47]
 [ 0.63 -0.24 -0.13  0.68 -0.36  0.55 -0.16  0.59]]


In [4]:
import numpy as np

def apply_convolution(input_matrix, kernel, stride=1, padding_type='same'):
    input_size = np.array(input_matrix.shape)
    kernel_size = np.array(kernel.shape)

    if padding_type == 'same':
        pad_h = (kernel_size[0] - 1) // 2
        pad_w = (kernel_size[1] - 1) // 2
        input_padded = np.pad(input_matrix, ((pad_h, pad_h), (pad_w, pad_w)), mode='constant', constant_values=0)
    elif padding_type == 'valid':
        pad_h, pad_w = 0, 0
        input_padded = input_matrix  # No padding applied
    else:
        raise ValueError("Invalid padding type. Use 'same' or 'valid'.")

    padded_size = np.array(input_padded.shape)

    output_h = ((padded_size[0] - kernel_size[0]) // stride) + 1
    output_w = ((padded_size[1] - kernel_size[1]) // stride) + 1

    output_matrix = np.zeros((output_h, output_w))

    for i in range(0, output_h):
        for j in range(0, output_w):
            region = input_padded[i * stride : i * stride + kernel_size[0], j * stride : j * stride + kernel_size[1]]
            output_matrix[i, j] = np.sum(region * kernel)

    return output_matrix

# Example Input Image (8x8) - Replace with your own matrix
input_matrix = np.array([
    [0.1, 0.3, 0.5, 0.7, 0.2, 0.9, 0.4, 0.8],
    [0.6, 0.2, 0.8, 0.1, 0.5, 0.7, 0.3, 0.4],
    [0.9, 0.4, 0.6, 0.3, 0.8, 0.2, 0.7, 0.1],
    [0.5, 0.8, 0.1, 0.4, 0.6, 0.9, 0.2, 0.3],
    [0.7, 0.1, 0.3, 0.8, 0.2, 0.4, 0.9, 0.6],
    [0.2, 0.9, 0.4, 0.7, 0.1, 0.5, 0.3, 0.8],
    [0.3, 0.5, 0.7, 0.2, 0.9, 0.4, 0.6, 0.1],
    [0.8, 0.1, 0.2, 0.6, 0.3, 0.7, 0.5, 0.9]
])

# Example Kernel (3x3)
kernel = np.array([
    [0.2, -0.5, 0.3],
    [-0.4, 0.8, -0.1],
    [0.6, -0.3, 0.5]
])

# Change stride and padding type as needed
stride = 1
padding_type = 'valid'  # Can be 'valid' or 'same'

# Apply Convolution
output_matrix = apply_convolution(input_matrix, kernel, stride, padding_type)

# Print the output
print("Convolution Output Matrix:")
print(output_matrix)


Convolution Output Matrix:
[[ 0.58  0.78  0.19  0.64  0.81  0.1 ]
 [ 0.27  0.61  0.42  0.99 -0.2   1.21]
 [ 1.13 -0.04  0.47  0.57  1.18 -0.24]
 [-0.45  1.12  0.58  0.49 -0.06  1.28]
 [ 1.16  0.19  0.92 -0.02  1.16 -0.12]
 [ 0.47  0.83 -0.36  1.46 -0.02  1.22]]


In [5]:
import numpy as np

def apply_convolution(input_matrix, kernel, stride=1, padding_type='same'):
    input_size = np.array(input_matrix.shape)
    kernel_size = np.array(kernel.shape)

    # Determine padding size
    if padding_type == 'same':
        pad_h = (kernel_size[0] - 1) // 2
        pad_w = (kernel_size[1] - 1) // 2
    elif padding_type == 'full':
        pad_h = kernel_size[0] - 1
        pad_w = kernel_size[1] - 1
    elif padding_type == 'valid':
        pad_h, pad_w = 0, 0
    else:
        raise ValueError("Invalid padding type. Use 'same', 'valid', or 'full'.")

    # Apply zero padding
    input_padded = np.pad(input_matrix, ((pad_h, pad_h), (pad_w, pad_w)), mode='constant', constant_values=0)
    
    padded_size = np.array(input_padded.shape)

    # Compute output dimensions
    output_h = ((padded_size[0] - kernel_size[0]) // stride) + 1
    output_w = ((padded_size[1] - kernel_size[1]) // stride) + 1

    output_matrix = np.zeros((output_h, output_w))

    # Perform convolution operation
    for i in range(0, output_h):
        for j in range(0, output_w):
            region = input_padded[i * stride : i * stride + kernel_size[0], j * stride : j * stride + kernel_size[1]]
            output_matrix[i, j] = np.sum(region * kernel)

    return output_matrix

# Example Input Image (8x8)
input_matrix = np.array([
    [0.1, 0.3, 0.5, 0.7, 0.2, 0.9, 0.4, 0.8],
    [0.6, 0.2, 0.8, 0.1, 0.5, 0.7, 0.3, 0.4],
    [0.9, 0.4, 0.6, 0.3, 0.8, 0.2, 0.7, 0.1],
    [0.5, 0.8, 0.1, 0.4, 0.6, 0.9, 0.2, 0.3],
    [0.7, 0.1, 0.3, 0.8, 0.2, 0.4, 0.9, 0.6],
    [0.2, 0.9, 0.4, 0.7, 0.1, 0.5, 0.3, 0.8],
    [0.3, 0.5, 0.7, 0.2, 0.9, 0.4, 0.6, 0.1],
    [0.8, 0.1, 0.2, 0.6, 0.3, 0.7, 0.5, 0.9]
])

# Example Kernel (3x3)
kernel = np.array([
    [0.2, -0.5, 0.3],
    [-0.4, 0.8, -0.1],
    [0.6, -0.3, 0.5]
])

# Change stride and padding type as needed
stride = 1
padding_type = 'full'  # Options: 'valid', 'same', 'full'

# Apply Convolution
output_matrix = apply_convolution(input_matrix, kernel, stride, padding_type)

# Print the output
print("Convolution Output Matrix:")
print(output_matrix)


Convolution Output Matrix:
[[ 0.05  0.12  0.22  0.38  0.19  0.81  0.05  0.82  0.    0.48]
 [ 0.29 -0.03  0.85  0.14  1.04  0.05  0.84  0.41  0.54 -0.08]
 [ 0.42  0.43  0.58  0.78  0.19  0.64  0.81  0.1   0.27  0.06]
 [ 0.34  0.69  0.27  0.61  0.42  0.99 -0.2   1.21 -0.31  0.22]
 [ 0.57 -0.17  1.13 -0.04  0.47  0.57  1.18 -0.24  0.61  0.26]
 [ 0.18  0.93 -0.45  1.12  0.58  0.49 -0.06  1.28 -0.05  0.3 ]
 [ 0.34 -0.09  1.16  0.19  0.92 -0.02  1.16 -0.12  0.73 -0.14]
 [ 0.43  0.17  0.47  0.83 -0.36  1.46 -0.02  1.22 -0.47  0.66]
 [ 0.01  0.63 -0.24 -0.13  0.68 -0.36  0.55 -0.16  0.59 -0.34]
 [ 0.24 -0.37  0.17  0.1  -0.17  0.18 -0.14  0.16 -0.35  0.18]]


In [6]:
import numpy as np

def apply_convolution(input_matrix, kernel, stride=1, padding_type='same', verbose=True):
    input_matrix = np.array(input_matrix)
    kernel = np.array(kernel)
    
    kernel_size = kernel.shape[0]
    input_size = input_matrix.shape[0]

    # Determine padding size based on type
    if padding_type == 'same':
        pad_size = (kernel_size - 1) // 2  # Keeps output size same as input
    elif padding_type == 'full':
        pad_size = kernel_size - 1  # Expands output size
    elif padding_type == 'valid':
        pad_size = 0  # No padding
    else:
        raise ValueError("Invalid padding type! Choose 'same', 'valid', or 'full'.")

    # Apply padding
    padded_matrix = np.pad(input_matrix, pad_size, mode='constant', constant_values=0)
    padded_size = padded_matrix.shape[0]

    if verbose:
        print(f"\n🔹 Padded Input Matrix ({padding_type} padding, pad={pad_size}):\n", padded_matrix)

    # Compute output size
    output_size = ((padded_size - kernel_size) // stride) + 1
    output_matrix = np.zeros((output_size, output_size))

    # Perform convolution
    for i in range(output_size):
        for j in range(output_size):
            row_start = i * stride
            row_end = row_start + kernel_size
            col_start = j * stride
            col_end = col_start + kernel_size
            
            # Extract region
            region = padded_matrix[row_start:row_end, col_start:col_end]
            
            # Compute convolution (element-wise multiplication + sum)
            conv_value = np.sum(region * kernel)
            output_matrix[i, j] = conv_value

            # Print intermediate steps
            if verbose:
                print(f"\nStep [{i},{j}]:")
                print("Region Extracted:")
                print(region)
                print("Element-wise Multiplication with Kernel:")
                print(region * kernel)
                print(f"Sum: {conv_value}")

    print("\n🔹 Final Output Matrix:")
    print(output_matrix)
    return output_matrix

# Example Matrices
input_matrix = [
    [0.1, 0.3, 0.5, 0.7, 0.2, 0.9, 0.4, 0.8],
    [0.6, 0.2, 0.8, 0.1, 0.5, 0.7, 0.3, 0.4],
    [0.9, 0.4, 0.6, 0.3, 0.8, 0.2, 0.7, 0.1],
    [0.5, 0.8, 0.1, 0.4, 0.6, 0.9, 0.2, 0.3],
    [0.7, 0.1, 0.3, 0.8, 0.2, 0.4, 0.9, 0.6],
    [0.2, 0.9, 0.4, 0.7, 0.1, 0.5, 0.3, 0.8],
    [0.3, 0.5, 0.7, 0.2, 0.9, 0.4, 0.6, 0.1],
    [0.8, 0.1, 0.2, 0.6, 0.3, 0.7, 0.5, 0.9]
]

kernel = [
    [0.2, -0.5, 0.3],
    [-0.4, 0.8, -0.1],
    [0.6, -0.3, 0.5]
]

# Run convolution with full padding
apply_convolution(input_matrix, kernel, stride=1, padding_type='full')



🔹 Padded Input Matrix (full padding, pad=2):
 [[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.1 0.3 0.5 0.7 0.2 0.9 0.4 0.8 0.  0. ]
 [0.  0.  0.6 0.2 0.8 0.1 0.5 0.7 0.3 0.4 0.  0. ]
 [0.  0.  0.9 0.4 0.6 0.3 0.8 0.2 0.7 0.1 0.  0. ]
 [0.  0.  0.5 0.8 0.1 0.4 0.6 0.9 0.2 0.3 0.  0. ]
 [0.  0.  0.7 0.1 0.3 0.8 0.2 0.4 0.9 0.6 0.  0. ]
 [0.  0.  0.2 0.9 0.4 0.7 0.1 0.5 0.3 0.8 0.  0. ]
 [0.  0.  0.3 0.5 0.7 0.2 0.9 0.4 0.6 0.1 0.  0. ]
 [0.  0.  0.8 0.1 0.2 0.6 0.3 0.7 0.5 0.9 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]]

Step [0,0]:
Region Extracted:
[[0.  0.  0. ]
 [0.  0.  0. ]
 [0.  0.  0.1]]
Element-wise Multiplication with Kernel:
[[ 0.   -0.    0.  ]
 [-0.    0.   -0.  ]
 [ 0.   -0.    0.05]]
Sum: 0.05

Step [0,1]:
Region Extracted:
[[0.  0.  0. ]
 [0.  0.  0. ]
 [0.  0.1 0.3]]
Element-wise Multiplication with Kernel:
[[ 0.   -0.    0.  ]
 [-0.    

array([[ 0.05,  0.12,  0.22,  0.38,  0.19,  0.81,  0.05,  0.82,  0.  ,
         0.48],
       [ 0.29, -0.03,  0.85,  0.14,  1.04,  0.05,  0.84,  0.41,  0.54,
        -0.08],
       [ 0.42,  0.43,  0.58,  0.78,  0.19,  0.64,  0.81,  0.1 ,  0.27,
         0.06],
       [ 0.34,  0.69,  0.27,  0.61,  0.42,  0.99, -0.2 ,  1.21, -0.31,
         0.22],
       [ 0.57, -0.17,  1.13, -0.04,  0.47,  0.57,  1.18, -0.24,  0.61,
         0.26],
       [ 0.18,  0.93, -0.45,  1.12,  0.58,  0.49, -0.06,  1.28, -0.05,
         0.3 ],
       [ 0.34, -0.09,  1.16,  0.19,  0.92, -0.02,  1.16, -0.12,  0.73,
        -0.14],
       [ 0.43,  0.17,  0.47,  0.83, -0.36,  1.46, -0.02,  1.22, -0.47,
         0.66],
       [ 0.01,  0.63, -0.24, -0.13,  0.68, -0.36,  0.55, -0.16,  0.59,
        -0.34],
       [ 0.24, -0.37,  0.17,  0.1 , -0.17,  0.18, -0.14,  0.16, -0.35,
         0.18]])

In [1]:
import numpy as np

def apply_convolution(input_matrix, kernel, stride=1, padding_type='same'):
    input_size = np.array(input_matrix.shape)
    kernel_size = np.array(kernel.shape)

    if padding_type == 'same':
        pad_h = (kernel_size[0] - 1) // 2
        pad_w = (kernel_size[1] - 1) // 2
        input_padded = np.pad(input_matrix, ((pad_h, pad_h), (pad_w, pad_w)), mode='constant', constant_values=0)
    elif padding_type == 'valid':
        pad_h, pad_w = 0, 0
        input_padded = input_matrix  # No padding applied
    else:
        raise ValueError("Invalid padding type. Use 'same' or 'valid'.")

    padded_size = np.array(input_padded.shape)

    output_h = ((padded_size[0] - kernel_size[0]) // stride) + 1
    output_w = ((padded_size[1] - kernel_size[1]) // stride) + 1

    output_matrix = np.zeros((output_h, output_w))

    for i in range(0, output_h):
        for j in range(0, output_w):
            region = input_padded[i * stride : i * stride + kernel_size[0], j * stride : j * stride + kernel_size[1]]
            output_matrix[i, j] = np.sum(region * kernel)

    return output_matrix

# Example Input Image (8x8) - Replace with your own matrix
input_matrix = np.array([
    [0.1, 0.3, 0.5, 0.7, 0.2, 0.9, 0.4, 0.8],
    [0.6, 0.2, 0.8, 0.1, 0.5, 0.7, 0.3, 0.4],
    [0.9, 0.4, 0.6, 0.3, 0.8, 0.2, 0.7, 0.1],
    [0.5, 0.8, 0.1, 0.4, 0.6, 0.9, 0.2, 0.3],
    [0.7, 0.1, 0.3, 0.8, 0.2, 0.4, 0.9, 0.6],
    [0.2, 0.9, 0.4, 0.7, 0.1, 0.5, 0.3, 0.8],
    [0.3, 0.5, 0.7, 0.2, 0.9, 0.4, 0.6, 0.1],
    [0.8, 0.1, 0.2, 0.6, 0.3, 0.7, 0.5, 0.9]
])

# Example Kernel (3x3)
kernel = np.array([
    [0.2, -0.5, 0.3],
    [-0.4, 0.8, -0.1],
    [0.6, -0.3, 0.5]
])

# Change stride and padding type as needed
stride = 2
padding_type = 'same'  # Can be 'valid' or 'same'

# Apply Convolution
output_matrix = apply_convolution(input_matrix, kernel, stride, padding_type)

# Print the output
print("Convolution Output Matrix:")
print(output_matrix)


Convolution Output Matrix:
[[-0.03  0.14  0.05  0.41]
 [ 0.69  0.61  0.99  1.21]
 [ 0.93  1.12  0.49  1.28]
 [ 0.17  0.83  1.46  1.22]]


In [2]:
import numpy as np

def apply_convolution(input_matrix, kernel, stride=1, padding_type='same'):
    input_size = np.array(input_matrix.shape)
    kernel_size = np.array(kernel.shape)

    # Determine padding size
    if padding_type == 'same':
        pad_h = (kernel_size[0] - 1) // 2
        pad_w = (kernel_size[1] - 1) // 2
        input_padded = np.pad(input_matrix, ((pad_h, pad_h), (pad_w, pad_w)), mode='constant', constant_values=0)
    elif padding_type == 'valid':
        pad_h, pad_w = 0, 0
        input_padded = input_matrix  # No padding applied
    else:
        raise ValueError("Invalid padding type. Use 'same' or 'valid'.")

    print("\nPadded Input Matrix:")
    print(input_padded)

    # Compute output dimensions
    padded_size = np.array(input_padded.shape)
    output_h = ((padded_size[0] - kernel_size[0]) // stride) + 1
    output_w = ((padded_size[1] - kernel_size[1]) // stride) + 1

    output_matrix = np.zeros((output_h, output_w))

    print("\nIntermediate Convolution Steps:")

    # Convolution operation
    for i in range(output_h):
        for j in range(output_w):
            # Extract region from padded input
            region = input_padded[i * stride : i * stride + kernel_size[0], j * stride : j * stride + kernel_size[1]]

            # Compute element-wise multiplication and summation
            conv_value = np.sum(region * kernel)
            output_matrix[i, j] = conv_value

            # Print the region and its result
            print(f"\nRegion at Output[{i},{j}]:")
            print(region)
            print(f"Convolution Result: {conv_value}")

    print("\nFinal Convolution Output Matrix:")
    print(output_matrix)

    return output_matrix


# Example Input Image (8x8)
input_matrix = np.array([
    [0.1, 0.3, 0.5, 0.7, 0.2, 0.9, 0.4, 0.8],
    [0.6, 0.2, 0.8, 0.1, 0.5, 0.7, 0.3, 0.4],
    [0.9, 0.4, 0.6, 0.3, 0.8, 0.2, 0.7, 0.1],
    [0.5, 0.8, 0.1, 0.4, 0.6, 0.9, 0.2, 0.3],
    [0.7, 0.1, 0.3, 0.8, 0.2, 0.4, 0.9, 0.6],
    [0.2, 0.9, 0.4, 0.7, 0.1, 0.5, 0.3, 0.8],
    [0.3, 0.5, 0.7, 0.2, 0.9, 0.4, 0.6, 0.1],
    [0.8, 0.1, 0.2, 0.6, 0.3, 0.7, 0.5, 0.9]
])

# Example Kernel (3x3)
kernel = np.array([
    [0.2, -0.5, 0.3],
    [-0.4, 0.8, -0.1],
    [0.6, -0.3, 0.5]
])

# Set stride and padding type
stride = 1
padding_type = 'same'

# Apply Convolution
output_matrix = apply_convolution(input_matrix, kernel, stride, padding_type)



Padded Input Matrix:
[[0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.1 0.3 0.5 0.7 0.2 0.9 0.4 0.8 0. ]
 [0.  0.6 0.2 0.8 0.1 0.5 0.7 0.3 0.4 0. ]
 [0.  0.9 0.4 0.6 0.3 0.8 0.2 0.7 0.1 0. ]
 [0.  0.5 0.8 0.1 0.4 0.6 0.9 0.2 0.3 0. ]
 [0.  0.7 0.1 0.3 0.8 0.2 0.4 0.9 0.6 0. ]
 [0.  0.2 0.9 0.4 0.7 0.1 0.5 0.3 0.8 0. ]
 [0.  0.3 0.5 0.7 0.2 0.9 0.4 0.6 0.1 0. ]
 [0.  0.8 0.1 0.2 0.6 0.3 0.7 0.5 0.9 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]]

Intermediate Convolution Steps:

Region at Output[0,0]:
[[0.  0.  0. ]
 [0.  0.1 0.3]
 [0.  0.6 0.2]]
Convolution Result: -0.02999999999999997

Region at Output[0,1]:
[[0.  0.  0. ]
 [0.3 0.5 0.7]
 [0.2 0.8 0.1]]
Convolution Result: 0.14

Region at Output[0,2]:
[[0.  0.  0. ]
 [0.7 0.2 0.9]
 [0.1 0.5 0.7]]
Convolution Result: 0.050000000000000044

Region at Output[0,3]:
[[0.  0.  0. ]
 [0.9 0.4 0.8]
 [0.7 0.3 0.4]]
Convolution Result: 0.41000000000000003

Region at Output[1,0]:
[[0.  0.6 0.2]
 [0.  0.9 0.4]
 [0.  0.5 0.8]]
Convolution Resul

In [5]:
import numpy as np

def apply_convolution(input_matrix, kernel, stride=1, padding_type='same'):
    input_size = np.array(input_matrix.shape)
    kernel_size = np.array(kernel.shape)

    # Determine padding size
    if padding_type == 'same':
        pad_h = (kernel_size[0] - 1) // 2
        pad_w = (kernel_size[1] - 1) // 2
        input_padded = np.pad(input_matrix, ((pad_h, pad_h), (pad_w, pad_w)), mode='constant', constant_values=0)
    elif padding_type == 'valid':
        pad_h, pad_w = 0, 0
        input_padded = input_matrix  # No padding applied
    else:
        raise ValueError("Invalid padding type. Use 'same' or 'valid'.")

    print("\nPadded Input Matrix:")
    print(input_padded)

    # Compute output dimensions
    padded_size = np.array(input_padded.shape)
    output_h = ((padded_size[0] - kernel_size[0]) // stride) + 1
    output_w = ((padded_size[1] - kernel_size[1]) // stride) + 1

    output_matrix = np.zeros((output_h, output_w))

    print("\nIntermediate Convolution Steps:")

    # Convolution operation
    for i in range(output_h):
        for j in range(output_w):
            # Extract region from padded input
            region = input_padded[i * stride : i * stride + kernel_size[0], j * stride : j * stride + kernel_size[1]]

            # Compute element-wise multiplication and summation
            conv_value = np.sum(region * kernel)
            output_matrix[i, j] = conv_value

            # Print the region and its result
            print(f"\nRegion at Output[{i},{j}]:")
            print(region)
            print(f"Convolution Result: {conv_value}")

    print("\nFinal Convolution Output Matrix:")
    print(output_matrix)

    return output_matrix


# Example Input Image (8x8)
input_matrix = np.array([
    [0.1, 0.3, 0.5, 0.7, 0.2, 0.9, 0.4, 0.8],
    [0.6, 0.2, 0.8, 0.1, 0.5, 0.7, 0.3, 0.4],
    [0.9, 0.4, 0.6, 0.3, 0.8, 0.2, 0.7, 0.1],
    [0.5, 0.8, 0.1, 0.4, 0.6, 0.9, 0.2, 0.3],
    [0.7, 0.1, 0.3, 0.8, 0.2, 0.4, 0.9, 0.6],
    [0.2, 0.9, 0.4, 0.7, 0.1, 0.5, 0.3, 0.8],
    [0.3, 0.5, 0.7, 0.2, 0.9, 0.4, 0.6, 0.1],
    [0.8, 0.1, 0.2, 0.6, 0.3, 0.7, 0.5, 0.9]
])

# Example Kernel (3x3)
kernel = np.array([
    [0.2, -0.5, 0.3],
    [-0.4, 0.8, -0.1],
    [0.6, -0.3, 0.5]
])

# Set stride and padding type
stride = 1
padding_type = 'same'

# Apply Convolution
output_matrix = apply_convolution(input_matrix, kernel, stride, padding_type)



Padded Input Matrix:
[[0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.1 0.3 0.5 0.7 0.2 0.9 0.4 0.8 0. ]
 [0.  0.6 0.2 0.8 0.1 0.5 0.7 0.3 0.4 0. ]
 [0.  0.9 0.4 0.6 0.3 0.8 0.2 0.7 0.1 0. ]
 [0.  0.5 0.8 0.1 0.4 0.6 0.9 0.2 0.3 0. ]
 [0.  0.7 0.1 0.3 0.8 0.2 0.4 0.9 0.6 0. ]
 [0.  0.2 0.9 0.4 0.7 0.1 0.5 0.3 0.8 0. ]
 [0.  0.3 0.5 0.7 0.2 0.9 0.4 0.6 0.1 0. ]
 [0.  0.8 0.1 0.2 0.6 0.3 0.7 0.5 0.9 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]]

Intermediate Convolution Steps:

Region at Output[0,0]:
[[0.  0.  0. ]
 [0.  0.1 0.3]
 [0.  0.6 0.2]]
Convolution Result: -0.02999999999999997

Region at Output[0,1]:
[[0.  0.  0. ]
 [0.1 0.3 0.5]
 [0.6 0.2 0.8]]
Convolution Result: 0.85

Region at Output[0,2]:
[[0.  0.  0. ]
 [0.3 0.5 0.7]
 [0.2 0.8 0.1]]
Convolution Result: 0.14

Region at Output[0,3]:
[[0.  0.  0. ]
 [0.5 0.7 0.2]
 [0.8 0.1 0.5]]
Convolution Result: 1.0399999999999998

Region at Output[0,4]:
[[0.  0.  0. ]
 [0.7 0.2 0.9]
 [0.1 0.5 0.7]]
Convolution Result: 0.050000000000

In [1]:
import numpy as np

def apply_convolution(input_matrix, kernel, stride=3, padding_type='same'):
    input_size = np.array(input_matrix.shape)
    kernel_size = np.array(kernel.shape)

    # Determine padding size
    if padding_type == 'same':
        pad_h = 1  # Precomputed same padding
        pad_w = 1
        input_padded = np.pad(input_matrix, ((pad_h, pad_h), (pad_w, pad_w)), mode='constant', constant_values=0)
    elif padding_type == 'valid':
        pad_h, pad_w = 0, 0
        input_padded = input_matrix  # No padding applied
    else:
        raise ValueError("Invalid padding type. Use 'same' or 'valid'.")

    print("\nPadded Input Matrix:")
    print(input_padded)

    # Compute output dimensions
    padded_size = np.array(input_padded.shape)
    output_h = ((padded_size[0] - kernel_size[0]) // stride) + 1
    output_w = ((padded_size[1] - kernel_size[1]) // stride) + 1

    output_matrix = np.zeros((output_h, output_w))

    print("\nIntermediate Convolution Steps:")

    # Convolution operation
    for i in range(output_h):
        for j in range(output_w):
            # Extract region from padded input
            region = input_padded[i * stride : i * stride + kernel_size[0], j * stride : j * stride + kernel_size[1]]

            # Compute element-wise multiplication and summation
            conv_value = np.sum(region * kernel)
            output_matrix[i, j] = conv_value

            # Print the region and its result
            print(f"\nRegion at Output[{i},{j}]:")
            print(region)
            print(f"Convolution Result: {conv_value}")

    print("\nFinal Convolution Output Matrix:")
    print(output_matrix)

    return output_matrix

# Input Matrix (7x7)
input_matrix = np.array([
    [2, 3, 1, 5, 0, 1, 4],
    [6, 0, 2, 7, 3, 0, 0],
    [4, 8, 9, 1, 3, 6, 2],
    [7, 2, 5, 8, 0, 1, 9],
    [3, 4, 7, 2, 5, 8, 8],
    [0, 1, 3, 6, 8, 9, 7],
    [5, 2, 7, 1, 3, 4, 6]
])

# Kernel (3x3)
kernel = np.array([
    [0, 1, -1],
    [2, -2, 3],
    [1, 0, -1]
])

# Apply Convolution
output_matrix = apply_convolution(input_matrix, kernel, stride=3, padding_type='same')



Padded Input Matrix:
[[0 0 0 0 0 0 0 0 0]
 [0 2 3 1 5 0 1 4 0]
 [0 6 0 2 7 3 0 0 0]
 [0 4 8 9 1 3 6 2 0]
 [0 7 2 5 8 0 1 9 0]
 [0 3 4 7 2 5 8 8 0]
 [0 0 1 3 6 8 9 7 0]
 [0 5 2 7 1 3 4 6 0]
 [0 0 0 0 0 0 0 0 0]]

Intermediate Convolution Steps:

Region at Output[0,0]:
[[0 0 0]
 [0 2 3]
 [0 6 0]]
Convolution Result: 5

Region at Output[0,1]:
[[0 0 0]
 [1 5 0]
 [2 7 3]]
Convolution Result: -9

Region at Output[0,2]:
[[0 0 0]
 [1 4 0]
 [0 0 0]]
Convolution Result: -6

Region at Output[1,0]:
[[0 4 8]
 [0 7 2]
 [0 3 4]]
Convolution Result: -16

Region at Output[1,1]:
[[9 1 3]
 [5 8 0]
 [7 2 5]]
Convolution Result: -6

Region at Output[1,2]:
[[6 2 0]
 [1 9 0]
 [8 8 0]]
Convolution Result: -6

Region at Output[2,0]:
[[0 0 1]
 [0 5 2]
 [0 0 0]]
Convolution Result: -5

Region at Output[2,1]:
[[3 6 8]
 [7 1 3]
 [0 0 0]]
Convolution Result: 19

Region at Output[2,2]:
[[9 7 0]
 [4 6 0]
 [0 0 0]]
Convolution Result: 3

Final Convolution Output Matrix:
[[  5.  -9.  -6.]
 [-16.  -6.  -6.]
 [ -5.  19.